@testset "measuring pfx/induced/total break from a trajectory (§8 V&V-5)" begin
    @testset "cd_at interpolates and clamps" begin
        aero = MeasuredDragAero([0.0, 1.0, 2.0], [0.30, 0.40, 0.30],
                                BaseballProperties(), 1.204)
        @test cd_at(aero, 0.0) == 0.30
        @test cd_at(aero, 0.5) ≈ 0.35        # halfway between 0.30 and 0.40
        @test cd_at(aero, 1.0) == 0.40
        @test cd_at(aero, -5.0) == 0.30      # clamped below the first sample
        @test cd_at(aero, 50.0) == 0.30      # clamped above the last sample
    end

    @testset "MeasuredDragAero has zero lift and side force" begin
        aero = MeasuredDragAero([0.0, 1.0], [0.35, 0.35], BaseballProperties(), 1.204)
        s = BallState(; position = (0.0, 0.0, 1.0), velocity = (30.0, 5.0, -2.0),
                     spin = (0.0, 0.0, 200.0), time = 0.5)
        F, M = aero(s)
        # Drag opposes velocity exactly — no component perpendicular to it.
        v̂ = s.v ./ sqrt(sum(abs2, s.v))
        @test collect(F ./ sqrt(sum(abs2, F))) ≈ collect(.-v̂)
        @test M == (0.0, 0.0, 0.0)

        # At rest there is nothing to measure a direction from.
        s0 = BallState(; position = (0.0, 0.0, 1.0), velocity = (0.0, 0.0, 0.0))
        @test aero(s0) == ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
    end

    @testset "row_at_x interpolates a recorded trajectory" begin
        data = Dict(:t => [0.0, 1.0, 2.0], :x => [0.0, 10.0, 20.0],
                   :y => [0.0, 1.0, 4.0], :z => [1.0, 1.0, 1.0],
                   :vx => [10.0, 10.0, 10.0], :vy => [1.0, 3.0, 3.0], :vz => [0.0, 0.0, 0.0])
        r = row_at_x(data, 5.0)     # halfway between rows 1 and 2
        @test r.t ≈ 0.5
        @test r.y ≈ 0.5
        @test r.vy ≈ 2.0

        @test row_at_x(data, 0.0) == (t = 0.0, x = 0.0, y = 0.0, z = 1.0,
                                      vx = 10.0, vy = 1.0, vz = 0.0)

        err = try
            row_at_x(data, 100.0)
            nothing
        catch e
            e
        end
        @test err isa ArgumentError
        @test occursin("100.0", err.msg)
        @test occursin("20.0", err.msg)
    end

    @testset "agrees with the analytic model's own no_magnus reference" begin
        # measure_break re-derives pfx/induced/total from a recorded C_D(t)
        # rather than from `no_magnus(aero)` directly. Feeding it a trajectory
        # generated BY the analytic model (constant C_D, so the two paths are
        # measuring the same physics two different ways) should reproduce
        # pitch_metrics's own numbers closely — the real cross-check that the
        # re-derivation is not quietly wrong.
        props = BaseballProperties()
        aero = CoefficientAero(props; CD = 0.35, CL_slope = 1.0)
        s0 = BallState(; position = (2.0, 0.0, 1.75), velocity = (38.99, 0.0, 0.0),
                       spin = spin_from_rpm((0.15, 0.0, 1.0), 2708.0))
        dt = 1.0e-4
        traj = simulate_trajectory(s0, props, aero; dt = dt, distance = PLATE_DISTANCE)

        data = Dict(:t => [b.t for b in traj], :x => [b.x[1] for b in traj],
                   :y => [b.x[2] for b in traj], :z => [b.x[3] for b in traj],
                   :vx => [b.v[1] for b in traj], :vy => [b.v[2] for b in traj],
                   :vz => [b.v[3] for b in traj], :CD => fill(0.35, length(traj)))

        mb = measure_break(data; dt = dt)
        pm = pitch_metrics(s0, props, aero; dt = dt)

        @test mb.release_x ≈ 2.0
        @test mb.release_speed ≈ speed(s0)
        @test mb.plate_x ≈ PLATE_DISTANCE atol = 1.0e-6
        @test mb.plate_speed ≈ pm.plate_speed atol = 1.0e-3

        atol = 1.0e-3    # metres — well under the mm-scale this run's own
                         # discretisation (row spacing, RK4 step) could plausibly cost
        @test mb.pfx_horizontal ≈ pm.pfx_horizontal atol = atol
        @test mb.pfx_vertical ≈ pm.pfx_vertical atol = atol
        @test mb.induced_horizontal ≈ pm.induced_horizontal atol = atol
        @test mb.induced_vertical ≈ pm.induced_vertical atol = atol
        @test mb.total_horizontal ≈ pm.total_horizontal atol = atol
        @test mb.total_vertical ≈ pm.total_vertical atol = atol

        # The reference points are consistent with the differences by
        # construction — a viewer draws the points, not just the gap to them.
        @test mb.actual_y - mb.pfx_ref_y ≈ mb.pfx_horizontal
        @test mb.actual_z - mb.pfx_ref_z ≈ mb.pfx_vertical
        @test mb.actual_y - mb.induced_ref_y ≈ mb.induced_horizontal
        @test mb.actual_z - mb.induced_ref_z ≈ mb.induced_vertical
        @test mb.actual_y - mb.total_ref_y ≈ mb.total_horizontal
        @test mb.actual_z - mb.total_ref_z ≈ mb.total_vertical
    end

    @testset "complains about missing columns and short data, not just crashes" begin
        @test_throws ArgumentError measure_break(Dict(:t => [0.0, 1.0]))

        data = Dict(:t => [0.0], :x => [0.0], :y => [0.0], :z => [1.0],
                   :vx => [30.0], :vy => [0.0], :vz => [0.0], :CD => [0.35])
        @test_throws ArgumentError measure_break(data)   # one row: nothing to fly
    end
end
