name = "BreakingBallLBM"
uuid = "43c67187-11ee-42cb-b648-a46700a2c615"
authors = ["breaking-ball-lbm contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
