# run.toml
resolution          = 40
domain              = 4.0
open_faces          = true
upstream            = 3.0
downstream          = 5.0
refine              = [3.0, 1.5] # [Level1, Level2]
refine_wake         = [1.0, 1.0]
distance            = 18.4404
spinup_flowthroughs = 3.0
snapshot            = 10
snapshot_stride     = 4
overview            = true
overview_stride     = 1      # 既定